### ISSUE TITLE
android version error

### ISSUE THREAD

**Issue by GiyeonLee** [timtraversy/new_version#74]
final elements = document.getElementsByClassName('hAyfc');

I always get error that says no elemet in this line of code.

**Comment by timtraversy** [comment]
Could I ask what your app ID is so I can check it in the play store?

**Comment by clinkchoi** [comment]
same issue here.
ID is com.clinkkr.nyapp

**Comment by GiyeonLee** [comment]
> Could I ask what your app ID is so I can check it in the play store?

my android app id is com.ftorbus.ruko

**Comment by workingscorpion** [comment]
same problem. anyone solved?

**Comment by timtraversy** [comment]
What's the exact error that you get? I checked those app IDs and the Play Store pages have that class name, so not sure why it would fail.

**Comment by ShinMyth** [comment]
Good

> What's the exact error that you get? I checked those app IDs and the Play Store pages have that class name, so not sure why it would fail.

Good day sir... i have the same problem with the author the problem comes from line 152 of the package its "Bad state: No element
![Screen Shot 2021-12-20 at 1 28 53 PM](https://user-images.githubusercontent.com/45448192/146716309-34a6785e-0df6-4edd-b4a6-6530c1838a15.png)
"

**Comment by clinkchoi** [comment]
it may caused by country of play store is other than US.
```
original code:

Future<VersionStatus?> _getAndroidStoreVersion(
PackageInfo packageInfo) async {
final id = androidId ?? packageInfo.packageName;
final uri = Uri.https("play.google.com", "/store/apps/details", {"id": "$id"});
```

When I tried making url with additional country option as below it worked.
`final uri = Uri.https("play.google.com", "/store/apps/details", {"id": "$id", "gl":"US"});`

**Comment by GiyeonLee** [comment]
> it may caused by country of play store is other than US.
> 
> ```
> original code:
> 
> Future<VersionStatus?> _getAndroidStoreVersion(
> PackageInfo packageInfo) async {
> final id = androidId ?? packageInfo.packageName;
> final uri = Uri.https("play.google.com", "/store/apps/details", {"id": "$id"});
> ```
> 
> When I tried making url with additional country option as below it worked. `final uri = Uri.https("play.google.com", "/store/apps/details", {"id": "$id", "gl":"US"});`

It also work for me. Thanks!

**Comment by timtraversy** [comment]
Thanks for the discovery! Is that `gl` parameter documented somewhere?

**Comment by clinkchoi** [comment]
> Thanks for the discovery! Is that `gl` parameter documented somewhere?

no document.
I'm not sure how but I knew there are parameter 'hl' for language and 'gl' for country. 

FYI, This issue occurred from around November and  same issue in similar module like upgrader.
Most people has no problem but problem in some specific country. (I'm form Korea)

Introducing country option for Android would be a solution for this in my humble opinion.
Thanks.

**Comment by timtraversy** [comment]
Thanks, I'll test this some more and make a change

**Comment by clinkchoi** [comment]
@timtraversy Sorry for late response. 
It seems to be ok since my app is publishing to both Korean and US store.

**Comment by shyun94** [comment]
@timtraversy Hi. I want to use this but this case should be solved. 

How about setting "gl" by settings?

**Comment by Abdusamad98** [comment]
![Screenshot 2022-05-28 112919](https://user-images.githubusercontent.com/48511954/170813450-6bd5c4bf-29fe-4f2f-8114-7efa3296064b.png)
I am having the same problem as above. Have you solved it? Please help with that

**Comment by tree1891** [comment]
_getAndroidStoreVersion function is modified.

`  
Future<VersionStatus?> _getAndroidStoreVersion(
      PackageInfo packageInfo) async {
    final id = androidId ?? packageInfo.packageName;
    final uri =
        Uri.https("play.google.com", "/store/apps/details", {"id": "$id", "hl": "en"});
    final response = await http.get(uri);
    if (response.statusCode != 200) {
      debugPrint('Can\'t find an app in the Play Store with the id: $id');
      return null;
    }
    final document = parse(response.body);

    String storeVersion = '0.0.0';
    String? releaseNotes;

    final additionalInfoElements = document.getElementsByClassName('hAyfc');
    if (additionalInfoElements.isNotEmpty) {
      final versionElement = additionalInfoElements.firstWhere(
            (elm) => elm.querySelector('.BgcNfc')!.text == 'Current Version',
      );
      storeVersion = versionElement.querySelector('.htlgb')!.text;

      final sectionElements = document.getElementsByClassName('W4P4ne');
      final releaseNotesElement = sectionElements.firstWhereOrNull(
            (elm) => elm.querySelector('.wSaTQd')!.text == 'What\'s New',
      );
      releaseNotes = releaseNotesElement
          ?.querySelector('.PHBdkd')
          ?.querySelector('.DWPxHb')
          ?.text;
    } else {
      final scriptElements = document.getElementsByTagName('script');
      final infoScriptElement = scriptElements.firstWhere(
            (elm) => elm.text.contains('key: \'ds:4\''),
      );

      final param = infoScriptElement.text.substring(20, infoScriptElement.text.length - 2)
          .replaceAll('key:', '"key":')
          .replaceAll('hash:', '"hash":')
          .replaceAll('data:', '"data":')
          .replaceAll('sideChannel:', '"sideChannel":')
          .replaceAll('\'', '"');
      final parsed = json.decode(param);
      final data =  parsed['data'];

      storeVersion = data[1][2][140][0][0][0];
      releaseNotes = data[1][2][144][1][1];
    }

    return VersionStatus._(
      localVersion: _getCleanVersion(packageInfo.version),
      storeVersion: _getCleanVersion(forceAppVersion ?? storeVersion),
      appStoreLink: uri.toString(),
      releaseNotes: releaseNotes,
    );
  }
`

**Comment by ankitpanwar8979** [comment]
For me, @tree1891 answer worked with just one change.
I have calendar permission in my app so I have to add one more `replaceAll` function.

```
final param = infoScriptElement.text.substring(20, infoScriptElement.text.length - 2)
          .replaceAll('key:', '"key":')
          .replaceAll('hash:', '"hash":')
          .replaceAll('data:', '"data":')
          .replaceAll('sideChannel:', '"sideChannel":')
          .replaceAll('\'', '"')
          .replaceAll('owners\"', 'owners');
```
Then it worked perfectly.
Still not sure if this data will be consistent or not but it worked for now.

**Comment by Abdusamad98** [comment]
@tree1891 and @ankitpanwar8979 thank you for helping very fast to me, it worked for me also. Tanks a lot
